Repository Deve-Tom/DouyinSimpleProject, pull requests merged in 2023-02, with the labels that each got.

#1 New Feature: Publish Video
  README.md
  conf.yaml
  config/config.go
  controller/common.go
  controller/video_controller.go
  dto/user_dto.go
  dto/video_dto.go
  public/default.jpg
  router/app.go
  service/video_service.go
  utils/utils.go
Labels: enhancement

#2 feature: publish list & feed
  README.md
  conf.yaml
  config/config.go
  controller/user_controller.go
  controller/video_controller.go
  dto/video_dto.go
  main.go
  middleware/jwt.go
  router/app.go
  service/user_service.go
  service/video_service.go
  utils/utils.go
Labels: enhancement

#5 feature: comment action and list
  README.md
  cmd/gen_code.go
  conf.yaml
  config/config.go
  controller/comment_controller.go
  controller/common.go
  controller/favorite_controller.go
  controller/video_controller.go
  dao/gen.go
  dao/t_comment.gen.go
  dao/t_user.gen.go
  dao/t_video.gen.go
  dto/comment_dto.go
  dto/user_dto.go
  dto/video_dto.go
  entity/comment.go
  entity/user.go
  entity/video.go
  router/app.go
  service/comment_service.go
  service/video_service.go
  utils/utils.go
Labels: bug, enhancement

#6 fix bugs
  README.md
  conf.yaml
  config/config.go
  controller/comment_controller.go
  controller/common.go
  controller/favorite_controller.go
  controller/video_controller.go
  router/app.go
  service/video_service.go
Labels: bug

#9 feature: follow/follower list
  README.md
  controller/follow_controller.go
  dto/user_dto.go
  dto/video_dto.go
  router/app.go
  service/comment_service.go
  service/follow_service.go
  service/user_service.go
Labels: enhancement
